//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zxcshibuya
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class shibuya1Entities2 : DbContext
    {
        public shibuya1Entities2()
            : base("name=shibuya1Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<direction> direction { get; set; }
        public virtual DbSet<logpass> logpass { get; set; }
        public virtual DbSet<price_cat> price_cat { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<ticket> ticket { get; set; }
    }
}
