//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zxcshibuya
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket
    {
        public int ticket_id { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public Nullable<int> id_price_cat { get; set; }
        public Nullable<int> id_direction { get; set; }
        public string start_station { get; set; }
        public string end_station { get; set; }
        public Nullable<int> price { get; set; }
        public int id_person { get; set; }
    
        public virtual direction direction { get; set; }
        public virtual logpass logpass { get; set; }
        public virtual price_cat price_cat { get; set; }
    }
}
